version: "3.9"
services:
  mysql:
    image: mysql:8.0.28-oracle
    container_name: weather-app-db
    env_file:
      - "./.env"
    environment:
      - MYSQL_ROOT_PASSWORD=weather-app-pass
    volumes:
      - weather-app-mysql-vol:/var/lib/mysql:rw
    networks:
      - weather-app-network

  web:
    container_name: weather-app-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"    
    environment:
      - CITY_JSON_FILE_PATH=${CITY_JSON_FILE_PATH:-/usr/src/weather-app/cities.json}
    env_file:
      - "./.env"
    networks:
      - weather-app-network
    depends_on:
      - mysql
  
volumes:
  weather-app-mysql-vol:
networks:
  weather-app-network:

