version: "3.9"

services:      
  web:
    container_name: weather-app-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APPLICATION_PORT}:3000
    environment:
      - CONTAINER_CITY_JSON_FILE_PATH=${CONTAINER_CITY_JSON_FILE_PATH:-/usr/src/weather-app/cities.json}
    env_file:
      - "./.env"
    networks:
      - weather-app-network
    volumes:
      - type: bind
        source: ${HOST_CITY_JSON_FILE_PATH:-./cities.json}
        target : ${CONTAINER_CITY_JSON_FILE_PATH:-/usr/src/weather-app/cities.json}
    depends_on: 
      mysql: 
        condition: service_healthy

  mysql:
    image: mysql:8.0.28-oracle
    container_name: weather-app-db    
    volumes:
      - weather-app-mysql-vol:/var/lib/mysql:rw 
    networks:
      - weather-app-network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}    
    healthcheck:
      test: ["CMD", "mysql","-h","localhost","-p${MYSQL_PASS}"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s      
volumes:
  weather-app-mysql-vol:
networks:
  weather-app-network: